### ISSUE TITLE
Documentation and examples for using labels as strings

### ISSUE THREAD

**Issue by m1gnus** [capnspacehook/whalewall#116]
With new versions of docker labels can be used only as strings. It would be really helpful to produce documentation and examples of using whalewall's labels as strings instead of use it as yaml data structures.

**Comment by capnspacehook** [comment]
Whalewall configs contained in Docker labels should already be strings, if you take a look at the example on the README '|' is the first character, meaning a multiline is used. Also, as far as I know Docker has always required the contents of labels to be a single string, though I'm not sure about that.

**Comment by capnspacehook** [comment]
Please open another issue if you have a problem using or configuring whalewall, thanks!

**Comment by m1gnus** [comment]
Sorry for being late in this, but i completely forgot to write it here. The problem was that i had also label in the form `-"label=value"`, and is forbidden to use this kind of convention together with the convention shown in your README file (`label: value`)

**Comment by capnspacehook** [comment]
Yeah docker compose doesn't like it when you mix formats
