### ISSUE TITLE
Remove rules of exited container

### ISSUE THREAD

**Issue by rgomezceis** [capnspacehook/whalewall#35]
When you have a stack and a container exited by itself, whalewall should remove all rules of this cointainer and also the element from map in nft table.

When you redeploy the stack with the container in exited state, you'll see something like this:

> ERR msg=error creating rules container.id=40b0ee127c68 container.name=openproject_seeder error=error adding container to database: constraint failed: UNIQUE constraint failed: containers.name (2067) stacktrace=github.com/capnspacehook/whalewall.(*RuleManager).createRules
	github.com/capnspacehook/whalewall/create.go:64
github.com/capnspacehook/whalewall.(*RuleManager).Start.func1
	github.com/capnspacehook/whalewall/manager.go:112

> ERR msg=error creating rules container.id=c95cc6bdc09c container.name=openproject_seeder error=error validating rules: error handling required container "openproject_cache": error flushing nftables commands: conn.Receive: netlink receive: file exists stacktrace=github.com/capnspacehook/whalewall.(*RuleManager).createRules
	github.com/capnspacehook/whalewall/create.go:64
github.com/capnspacehook/whalewall.(*RuleManager).Start.func1
	github.com/capnspacehook/whalewall/manager.go:112

The temporary solution is to stop the stack, restart whalewall container to force clean the rules of exited container and redeploy the stack.

**Comment by capnspacehook** [comment]
Thanks for reporting an issue! Can you build and try from #36 and tell me if that fixed it?

**Comment by rgomezceis** [comment]
> Thanks for reporting an issue! Can you build and try from #36 and tell me if that fixed it?

Works well now, you can merge it.
