### ISSUE TITLE
Source Port feature

### ISSUE THREAD

**Issue by rgomezceis** [capnspacehook/whalewall#37]
Is possible to implement source port for outgoing traffic? 
We have containers that use a single source port for sending traffic to other containers with random dest ports.

**Comment by capnspacehook** [comment]
It's definitely possible without too much effort I think. So you'd like to be able to create outbound rules that restrict traffic to a single source port and allow to any destination port?

I'm thinking I might modify the config, 'port' would get replaced with 'src_port' and 'dst_port'. Then you could create rules that enforce specific source ports, destination ports, or both. That sound good?

**Comment by rgomezceis** [comment]
That's correct.
