### ISSUE TITLE
Cleanup: May use .IgnoreIfMissing() for go-landlock

### ISSUE THREAD

**Issue by gnoack** [capnspacehook/whalewall#59]
Hello Andrew!

I have added a feature to the go-landlock library to simplify its use with file paths which are potentially missing: https://github.com/landlock-lsm/go-landlock/issues/7

You should be able to simplify your code in https://github.com/capnspacehook/whalewall/blob/master/cmd/whalewall/main.go#L150 by using

```
landlock.PathAccess(...).IgnoreIfMissing()
```

Thank you for using go-landlock and for making your project open source!

**Comment by capnspacehook** [comment]
That's very useful thanks!  Thank you for maintaining go-landlock!
