### ISSUE TITLE
Permit all outbound connectivity

### ISSUE THREAD

**Issue by MitchDrage** [capnspacehook/whalewall#99]
This is more of a 'how do I do _x_' than an actual issue.

I can't determine through the examples given, how I would be able to permit a container to access anything on the internet on any port and service, where it also has the requirement to have inbound rules - having whalewall.enabled=true set.

Is this something that is supported?

**Comment by capnspacehook** [comment]
Hmm, unfortunately I don't think this is possible right now. You'd have to create an output rule for every port, which is not ideal. I'm sure with logging you could figure out what ports your container needs, as I'm sure it doesn't need every port.

You do bring up a good point though, multiple ports should be able to be specified per rule.

**Comment by MitchDrage** [comment]
My container is a vulnerability scanner, so 2x 65535 (TCP and UDP) ports wouldn't work. :)

The container in question doens't actually need whalewall running - it connects outbound only. I've only got it there to use the 'output' rules to access another container.
So on that topic - If I switch this around - Is there another way to use 'mapped-rules' to allow input from this outbound-only container to access the container that is currently being accessed using output rules?

**Comment by capnspacehook** [comment]
I don't think so, containers can only be accessed by creating `output` rules. I did just push the ability to specify multiple ranges of destination ports though, that should solve your problem.

Something like this should fit your needs:

```yaml
output:
  - container: foo
    network: foo-net
    dst_ports:
      - 0-65535
 ```
